
server:
  port: 8095
  contextPath: /hr/api

logging:
  level:
    org.hr.controllers: INFO

entitymanager:
    packagesToScan: org.hr
spring:
    application:
        name: HumanResourceRS
    datasource:
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@windows10.server.com:1521:orcl
        username: hr
        password: hr
        initialize: true
        testWhileIdle: 1
        validationQuery: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.Oracle10gDialect
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
eureka:
    client:
        serviceUrl:
            defaultZone: http://windows10.server.com:8761/eureka/
    instance:
        preferIpAddress: true

ribbon:
    eureka:
        enabled: true
