
server:
  port: 8087
  contextPath: /orders/api

logging:
  level:
    org.orders.controllers: INFO

entitymanager:
    packagesToScan: org.orders
management:
    contextPath: /admin
spring:
    application:
        name: OrdersRS
    datasource:
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@windows10.server.com:1521:orcl
        username: OE
        password: oe
        initialize: true
        testWhileIdle: 1
        validationQuery: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.Oracle10gDialect
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    cloud:
        consul:
            host: consul-discovery
            port: 8500
            discovery:
                healthCheckPath: ${management.contextPath}/health
                healthCheckInterval: 15s
                instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
