
server:
  port: 8189
  contextPath: /sales/api

logging:
  level:
    org.sh.controllers: INFO

entitymanager:
    packagesToScan: org.sales
spring:
    zipkin:
        baseUrl: http://zipkin:9411
    datasource:
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@windows10.server.com:1521:orcl
        username: sh
        password: sh
        initialize: true
        testWhileIdle: 1
        validationQuery: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.Oracle10gDialect
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

eureka:
    client:
        serviceUrl:
            defaultZone: http://eurekaregistry:8761/eureka/
    instance:
        preferIpAddress: true

ribbon:
    eureka:
        enabled: true
