server:
  port: 8183
  contextPath: /videos/api

logging:
  level:
    org.orders.controllers: INFO
spring:
    zipkin:
        baseUrl: http://zipkin:9411
eureka:
    client:
        serviceUrl:
            defaultZone: http://eurekaregistry:8761/eureka/
    instance:
        preferIpAddress: true

ribbon:
    eureka:
        enabled: true
