
server:
  port: 8903
  contextPath: /v2/world/api

logging:
  level:
    org.world.rs.controllers: INFO
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

info:
  app:
    name: World RestFul Sevice V2
    description: Detail of Countrys, Citys, Region, Languages .... etc around the world.
    version: 2.0.1
    
entitymanager:
  packagesToScan: org.world.rs
spring:
  application:
    name: worldrs-v2
    instance_id: i003
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.3:3306/world
    username: root
    password: Aug#2017
    initialize: true
    testWhileIdle: 1
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.3:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
