
server:
  port: 8901
  contextPath: /v2/world/api

logging:
  level:
    org.world.rs.controllers: INFO
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    
entitymanager:
  packagesToScan: org.world.rs
spring:
  application:
    name: worldrs-v2
    instance_id: i001
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: Aug#2017
    initialize: true
    testWhileIdle: 1
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
